In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os

os.environ["KHISTO_BIN_DIR"] = (
    "/home/elouen/python/khisto-python/src/khiops/build/linux-gcc-debug/bin/khisto"
)
from khisto import histogram, histogram_table, ecdf_values_table

In [3]:
import random
import numpy as np

x = np.array([random.gauss(0, 1) for _ in range(1000)])

In [4]:
histogram(x)

<module 'array_api_compat.numpy' from '/home/elouen/python/khisto-python/.venv/lib/python3.12/site-packages/array_api_compat/numpy/__init__.py'> rrrrrrrrrr

(array([0.02036364, 0.094     , 0.20266667, 0.322     , 0.472     ,
        0.328     , 0.174     , 0.05142857]),
 array([-3.03125, -2.     , -1.5    , -0.75   , -0.25   ,  0.25   ,
         0.75   ,  1.75   ,  2.625  ]))

In [5]:
import jax

x = jax.numpy.array([random.gauss(0, 1) for _ in range(1000)])

INFO:2025-12-12 16:37:24,863:jax._src.xla_bridge:808: Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: libtpu.so: cannot open shared object file: No such file or directory
INFO:jax._src.xla_bridge:Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: libtpu.so: cannot open shared object file: No such file or directory
WARNING:2025-12-12 16:37:24,865:jax._src.xla_bridge:850: An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.
WARNING:jax._src.xla_bridge:An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.

In [6]:
histogram(x)

<module 'jax.numpy' from '/home/elouen/python/khisto-python/.venv/lib/python3.12/site-packages/jax/numpy/__init__.py'> rrrrrrrrrr

(Array([0.00862921, 0.07936   , 0.2575238 , 0.3712    , 0.224     ,
        0.11306667, 0.016     ], dtype=float32),
 Array([-3.515625, -2.125   , -1.34375 , -0.6875  ,  0.71875 ,  1.4375  ,
         1.90625 ,  3.21875 ], dtype=float32))

In [7]:
histogram(x.tolist())

<module 'ListBackend'> rrrrrrrrrr

([0.008629213483, 0.07936, 0.2575238095, 0.3712, 0.224, 0.1130666667, 0.016],
 [-3.515625, -2.125, -1.34375, -0.6875, 0.71875, 1.4375, 1.90625, 3.21875])

In [8]:
import pandas as pd

x = pd.Series([random.gauss(0, 1) for _ in range(1000)])
histogram(x)

<module 'SeriesBackend'> rrrrrrrrrr

(┌──────────────────────────┐
 |     Narwhals Series      |
 |--------------------------|
 |0    0.010159             |
 |1    0.043200             |
 |2    0.126000             |
 |3    0.266000             |
 |4    0.378000             |
 |5    0.242667             |
 |6    0.092000             |
 |7    0.018551             |
 |Name: data, dtype: float64|
 └──────────────────────────┘,
 ┌──────────────────────────┐
 |     Narwhals Series      |
 |--------------------------|
 |0   -2.992188             |
 |1   -2.500000             |
 |2   -1.875000             |
 |3   -1.375000             |
 |4   -0.375000             |
 |5    0.625000             |
 |6    1.375000             |
 |7    2.125000             |
 |8    2.664062             |
 |Name: data, dtype: float64|
 └──────────────────────────┘)

In [9]:
import polars as pl

x = pl.Series("x", [random.gauss(0, 1) for _ in range(1000)])
histogram(x, granularity=None)

[(┌────────────────────┐
  |  Narwhals Series   |
  |--------------------|
  |shape: (1,)         |
  |Series: 'data' [f64]|
  |[                   |
  |        0.149184    |
  |]                   |
  └────────────────────┘,
  ┌────────────────────┐
  |  Narwhals Series   |
  |--------------------|
  |shape: (2,)         |
  |Series: 'data' [f64]|
  |[                   |
  |        -3.3125     |
  |        3.390625    |
  |]                   |
  └────────────────────┘),
 (┌────────────────────┐
  |  Narwhals Series   |
  |--------------------|
  |shape: (3,)         |
  |Series: 'data' [f64]|
  |[                   |
  |        0.021333    |
  |        0.2385      |
  |        0.012944    |
  |]                   |
  └────────────────────┘,
  ┌────────────────────┐
  |  Narwhals Series   |
  |--------------------|
  |shape: (4,)         |
  |Series: 'data' [f64]|
  |[                   |
  |        -3.3125     |
  |        -2.0        |
  |        2.0         |
  |        3.390625    |
  |]                   |
  └────────────────────┘),
 (┌────────────────────┐
  |  Narwhals Series   |
  |--------------------|
  |shape: (5,)         |
  |Series: 'data' [f64]|
  |[                   |
  |        0.021333    |
  |        0.156       |
  |        0.332       |
  |        0.134       |
  |        0.012944    |
  |]                   |
  └────────────────────┘,
  ┌────────────────────┐
  |  Narwhals Series   |
  |--------------------|
  |shape: (6,)         |
  |Series: 'data' [f64]|
  |[                   |
  |        -3.3125     |
  |        -2.0        |
  |        -1.0        |
  |        1.0         |
  |        2.0         |
  |        3.390625    |
  |]                   |
  └────────────────────┘),
 (┌────────────────────┐
  |  Narwhals Series   |
  |--------------------|
  |shape: (8,)         |
  |Series: 'data' [f64]|
  |[                   |
  |        0.006154    |
  |        0.046       |
  |        0.112       |
  |        0.2         |
  |        0.332       |
  |        0.134       |
  |        0.03        |
  |        0.003368    |
  |]                   |
  └────────────────────┘,
  ┌────────────────────┐
  |  Narwhals Series   |
  |--------------------|
  |shape: (9,)         |
  |Series: 'data' [f64]|
  |[                   |
  |        -3.3125     |
  |        -2.5        |
  |        -2.0        |
  |        -1.5        |
  |        -1.0        |
  |        1.0         |
  |        2.0         |
  |        2.5         |
  |        3.390625    |
  |]                   |
  └────────────────────┘),
 (┌────────────────────┐
  |  Narwhals Series   |
  |--------------------|
  |shape: (8,)         |
  |Series: 'data' [f64]|
  |[                   |
  |        0.006154    |
  |        0.046       |
  |        0.121333    |
  |        0.248       |
  |        0.345714    |
  |        0.152       |
  |        0.046667    |
  |        0.003368    |
  |]                   |
  └────────────────────┘,
  ┌────────────────────┐
  |  Narwhals Series   |
  |--------------------|
  |shape: (9,)         |
  |Series: 'data' [f64]|
  |[                   |
  |        -3.3125     |
  |        -2.5        |
  |        -2.0        |
  |        -1.25       |
  |        -0.75       |
  |        1.0         |
  |        1.75        |
  |        2.5         |
  |        3.390625    |
  |]                   |
  └────────────────────┘),
 (┌────────────────────┐
  |  Narwhals Series   |
  |--------------------|
  |shape: (8,)         |
  |Series: 'data' [f64]|
  |[                   |
  |        0.002909    |
  |        0.0416      |
  |        0.121333    |
  |        0.248       |
  |        0.355077    |
  |        0.162286    |
  |        0.0544      |
  |        0.003938    |
  |]                   |
  └────────────────────┘,
  ┌────────────────────┐
  |  Narwhals Series   |
  |--------------------|
  |shape: (9,)         |
  |Series: 'data' [f64]|
  |[                   |
  |        -3.3125     |
  |        -2.625      |
  |        -2.0        |
  |        -1.25       |
  |        -0.75       |
  |        0.875       |
  |        1.75        |
  |        2.375       |
  |        3.390625    |
  |]                   |
  └────────────────────┘)]

In [10]:
histogram_table(x).to_native()

shape: (33, 9)
┌────────────┬────────────┬──────────┬───────────┬───┬──────────┬────────────┬─────────┬───────────┐
│ lower_boun ┆ upper_boun ┆ length   ┆ frequency ┆ … ┆ density  ┆ granularit ┆ is_best ┆ center    │
│ d          ┆ d          ┆ ---      ┆ ---       ┆   ┆ ---      ┆ y          ┆ ---     ┆ ---       │
│ ---        ┆ ---        ┆ f64      ┆ i64       ┆   ┆ f64      ┆ ---        ┆ bool    ┆ f64       │
│ f64        ┆ f64        ┆          ┆           ┆   ┆          ┆ i32        ┆         ┆           │
╞════════════╪════════════╪══════════╪═══════════╪═══╪══════════╪════════════╪═════════╪═══════════╡
│ -3.3125    ┆ -2.5       ┆ 0.8125   ┆ 5         ┆ … ┆ 0.006154 ┆ 3          ┆ false   ┆ -2.90625  │
│ -2.5       ┆ -2.0       ┆ 0.5      ┆ 23        ┆ … ┆ 0.046    ┆ 3          ┆ false   ┆ -2.25     │
│ -2.0       ┆ -1.5       ┆ 0.5      ┆ 56        ┆ … ┆ 0.112    ┆ 3          ┆ false   ┆ -1.75     │
│ -1.5       ┆ -1.0       ┆ 0.5      ┆ 100       ┆ … ┆ 0.2      ┆ 3          ┆ false   ┆ -1.25     │
│ -1.0       ┆ 1.0        ┆ 2.0      ┆ 664       ┆ … ┆ 0.332    ┆ 3          ┆ false   ┆ 0.0       │
│ …          ┆ …          ┆ …        ┆ …         ┆ … ┆ …        ┆ …          ┆ …       ┆ …         │
│ -3.3125    ┆ -2.0       ┆ 1.3125   ┆ 28        ┆ … ┆ 0.021333 ┆ 2          ┆ false   ┆ -2.65625  │
│ -2.0       ┆ -1.0       ┆ 1.0      ┆ 156       ┆ … ┆ 0.156    ┆ 2          ┆ false   ┆ -1.5      │
│ -1.0       ┆ 1.0        ┆ 2.0      ┆ 664       ┆ … ┆ 0.332    ┆ 2          ┆ false   ┆ 0.0       │
│ 1.0        ┆ 2.0        ┆ 1.0      ┆ 134       ┆ … ┆ 0.134    ┆ 2          ┆ false   ┆ 1.5       │
│ 2.0        ┆ 3.390625   ┆ 1.390625 ┆ 18        ┆ … ┆ 0.012944 ┆ 2          ┆ false   ┆ 2.6953125 │
└────────────┴────────────┴──────────┴───────────┴───┴──────────┴────────────┴─────────┴───────────┘

In [11]:
cum_df = ecdf_values_table(x).to_native()
cum_df

shape: (39, 5)
┌──────────┬─────────────┬─────────┬────────────────────────┬──────────────────────┐
│ position ┆ granularity ┆ is_best ┆ cumulative_probability ┆ cumulative_frequency │
│ ---      ┆ ---         ┆ ---     ┆ ---                    ┆ ---                  │
│ f64      ┆ i32         ┆ bool    ┆ f64                    ┆ i64                  │
╞══════════╪═════════════╪═════════╪════════════════════════╪══════════════════════╡
│ -3.3125  ┆ 0           ┆ false   ┆ 0.0                    ┆ 0                    │
│ 3.390625 ┆ 0           ┆ false   ┆ 1.0                    ┆ 1000                 │
│ -3.3125  ┆ 1           ┆ false   ┆ 0.0                    ┆ 0                    │
│ -2.0     ┆ 1           ┆ false   ┆ 0.028                  ┆ 28                   │
│ 2.0      ┆ 1           ┆ false   ┆ 0.982                  ┆ 982                  │
│ …        ┆ …           ┆ …       ┆ …                      ┆ …                    │
│ -0.75    ┆ 5           ┆ true    ┆ 0.243                  ┆ 243                  │
│ 0.875    ┆ 5           ┆ true    ┆ 0.82                   ┆ 820                  │
│ 1.75     ┆ 5           ┆ true    ┆ 0.962                  ┆ 962                  │
│ 2.375    ┆ 5           ┆ true    ┆ 0.996                  ┆ 996                  │
│ 3.390625 ┆ 5           ┆ true    ┆ 1.0                    ┆ 1000                 │
└──────────┴─────────────┴─────────┴────────────────────────┴──────────────────────┘

In [12]:
cum_df.filter(pl.col("granularity") == 0)

shape: (2, 5)
┌──────────┬─────────────┬─────────┬────────────────────────┬──────────────────────┐
│ position ┆ granularity ┆ is_best ┆ cumulative_probability ┆ cumulative_frequency │
│ ---      ┆ ---         ┆ ---     ┆ ---                    ┆ ---                  │
│ f64      ┆ i32         ┆ bool    ┆ f64                    ┆ i64                  │
╞══════════╪═════════════╪═════════╪════════════════════════╪══════════════════════╡
│ -3.3125  ┆ 0           ┆ false   ┆ 0.0                    ┆ 0                    │
│ 3.390625 ┆ 0           ┆ false   ┆ 1.0                    ┆ 1000                 │
└──────────┴─────────────┴─────────┴────────────────────────┴──────────────────────┘

In [13]:
ecdf_values_table([1.0, 2.0, 3.0, 4.0, 5.0], granularity="best").to_native()

pyarrow.Table
position: double
granularity: int32
is_best: bool
cumulative_probability: double
cumulative_frequency: int64
----
position: [[0.5,8]]
granularity: [[0,0]]
is_best: [[true,true]]
cumulative_probability: [[0,1]]
cumulative_frequency: [[0,5]]